name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    - name: Run Build Everywhere
      run: |
        if [ -f "pubspec.yaml" ]; then
          echo "=== Nakita sa Root Directory ==="
          flutter pub get
          flutter build apk --release
        elif [ -f "Anchor-Calculator/pubspec.yaml" ]; then
          echo "=== Nakita sa loob ng Subfolder ==="
          cd Anchor-Calculator
          flutter pub get
          flutter build apk --release
          cp build/app/outputs/flutter-apk/app-release.apk ../
        else
          echo "ERROR: Hindi talaga mahanap ang pubspec.yaml kahit saan!"
          exit 1
        fi

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: |
          app-release.apk
          build/app/outputs/flutter-apk/app-release.apk
          Anchor-Calculator/build/app/outputs/flutter-apk/app-release.apk
